"""Anomaly and cyber risk alert model generated by rule engines and detection models."""

import uuid
from decimal import Decimal
from typing import TYPE_CHECKING, Any, Dict, Optional
from sqlalchemy import ForeignKey, JSON, Numeric, String
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from backend.app.models.base import Base, TimestampMixin

if TYPE_CHECKING:
    from backend.app.models.account import Account
    from backend.app.models.transaction import Transaction
    from backend.app.models.case import Case


class Alert(Base, TimestampMixin):
    """Suspicious financial activity or cybercrime pattern trigger notification."""

    __tablename__ = "alerts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    alert_id: Mapped[str] = mapped_column(String(50), unique=True, index=True, nullable=False)
    alert_type: Mapped[str] = mapped_column(String(100), index=True, nullable=False)
    severity: Mapped[str] = mapped_column(String(20), index=True, nullable=False)
    status: Mapped[str] = mapped_column(String(30), default="OPEN", index=True, nullable=False)
    risk_score: Mapped[Decimal] = mapped_column(Numeric(5, 4), index=True, nullable=False)
    triggered_entity_type: Mapped[str] = mapped_column(String(50), index=True, nullable=False)
    triggered_entity_id: Mapped[str] = mapped_column(String(100), index=True, nullable=False)
    account_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("accounts.id", ondelete="SET NULL"),
        index=True,
        nullable=True,
    )
    transaction_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("transactions.id", ondelete="SET NULL"),
        index=True,
        nullable=True,
    )
    case_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("cases.id", ondelete="SET NULL"),
        index=True,
        nullable=True,
    )
    rule_flags: Mapped[Dict[str, Any] | None] = mapped_column(
        JSON().with_variant(JSONB, "postgresql"),
        nullable=True,
    )

    # Relationships
    account: Mapped[Optional["Account"]] = relationship("Account", back_populates="alerts", lazy="selectin")
    transaction: Mapped[Optional["Transaction"]] = relationship("Transaction", back_populates="alerts", lazy="selectin")
    case: Mapped[Optional["Case"]] = relationship("Case", back_populates="alerts", lazy="selectin")
